name: HyperDN
dependencies:
  - python=3.9  # Specify a compatible Python version
  - pip
  - pip:
      - numpy==1.24.3
      - pandas==1.5.3
      - matplotlib==3.7.1
      - scikit-learn==1.2.2
      - hydra--core==1.3.2
      - omegaconf==2.2.3
      - networkx==3.1
      - xgi==0.9.4
